### ISSUE TITLE
Typo "Version_last_translated"

### ISSUE THREAD

**Issue by bjornna** [openEHR/specifications-AM#3]
Below is the proposed change where I moved the first paragraph from the previous chapter. 
This is in master03-archetype_package.adoc 

==== Version_last_translated

The `_version_last_translated_` property is used to record a copy of the archetype_id.physical_id for each language, when the translation was carried out. This enables maintainers to know when new translations are needed for some or all languages.

This String property records the full version identifier (i.e. `ARCHETYPE`.`_archetype_id_`.`_version_id_`) at the time of last translation, enabling tools to determine if and when translations may be out of date.

**Comment by wolandscat** [comment]
Corrected in source; will be visible on push.
