### ISSUE TITLE
Wrong hierarchy level for headlines

### ISSUE THREAD

**Issue by jmewes** [openEHR/specifications-AM#6]
**Observed**

The headlines for the classes in the "aom_profile" package have the same level as their parent headline "Class definitions".

![Archetype_Object_Model_2__AOM2_](https://github.com/openEHR/specifications-AM/assets/5235584/2d7602e8-1032-4291-ad34-791fd92f7c96)

https://specifications.openehr.org/releases/AM/Release-2.2.0/AOM2.html#_class_definitions_3

**Expected**

The classes should have a one higher level than their parent headline.

**Comment by jmewes** [comment]
Same here: https://specifications.openehr.org/releases/BASE/Release-1.2.0/foundation_types.html#_class_definitions_7

**Comment by sebastian-iancu** [comment]
This was fixed in https://specifications.openehr.org/releases/AM/Release-2.3.0/AOM2.html#_class_definitions_3 and in https://specifications.openehr.org/releases/BASE/latest/foundation_types.html#_class_definitions_7
